/*
 * JFrame.java
 *
 * Created on 27 de mayo de 2005, 17:17
 */

package libreria;

/**
 *
 * @author  Fernando Lobos
 */

import java.util.ArrayList;
public class JFrame extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form JFrame */
    public JFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        getContentPane().add(jComboBox1, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      ArrayList<obj_seis_campos> arreglo_fono = new ArrayList<obj_seis_campos>();
      arreglo_fono.add(new obj_seis_campos("1","2","9","62093955","Fijo","1"));
      
      ArrayList<obj_ocho_campos> arreglo_dir = new ArrayList<obj_ocho_campos>();
      arreglo_dir.add(new obj_ocho_campos("1","245","Ciudad","Pje Gustavo Ale Flores","1","073","1","Laboral"));
      
      ArrayList<obj_tres_campos> arreglo_entidad = new ArrayList<obj_tres_campos>();
      arreglo_entidad.add(new obj_tres_campos("1","Alumno","1"));
      arreglo_entidad.add(new obj_tres_campos("2","Funcionario","0"));
      
      

      
      
      frm_entidades.guarda_entidad("13.715.383-1", "Oliveros","San Martin","José Antonio","25/12/2008","jose.oliveros@gmail.com",arreglo_entidad, arreglo_dir, arreglo_fono);
       
           
     //lista = frm_reloj_control.recupera_fecha_servidor();
      // lista = frm_reloj_control.inserta_marcaje("12.157.071-8","1");
      // lista = frm_entidades.guarda_entidad("13.715.383-1","Oliveros","San Martin","José Antonio", "01-02-2009", "jose.oliveros@gmail.com","2");
  
     // hola = 1;
      
      
      
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("deprecation")
	public static void main(String args[]) {
        new JFrame().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables
    
}
